### ISSUE TITLE
Update MUI to 5.12.1

### ISSUE THREAD

**Issue by simongitlitt** [julianmontague/ntnu-website-project_group01#58]

**Comment by simongitlitt** [comment]
If so, use commands:
npm install @mui/material@latest
npm install @mui/icons-material@latest

**Comment by julianmontague** [comment]
@simongitlitt can we consider this done? I see that [MUI is currently on 5.12.1](https://github.com/julianmontague/ntnu-website-project_group01/blob/34e4feb5e2fb9a38bb7ad75b34d4e2b6134a2bd7/webshop-frontend/package.json#L11).

**Comment by simongitlitt** [comment]
Yes. Closing it now.
